version: '3.8'

services:

  # DATABASE (MSSQL)
  sql:
    image: "mcr.microsoft.com/mssql/server:latest"
    container_name: sql_server
    user: root
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "y"
      SA_PASSWORD: "MyPass@word" # For local dev ONLY. DO NOT SHARE ANY CREDENTIALS
    volumes:
      - "//c/mount/sql:/var/opt/mssql/data"
    restart: on-failure:5

  # # PYTHON Server (For AI related Stuff)
  # python_backend:
  #   image: ghcr.io/awaazo/py_backend:${PY_VER}
  #   container_name: python_server
  #   ports:
  #     - "8500:8000"
  #   volumes:
  #     - "//c/backend_server/ServerFiles:/app/ServerFiles"

  # BACKEND ASP.NET Server
  backend:
    image: ghcr.io/awaazo/backend:${BACKEND_VER}
    container_name: backend_server
    ports:
      - "32773:80"
    links:
      - sql:database
      - sql:sql_server
      # - python_backend:py
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - "//c/backend_server/ServerFiles:/app/ServerFiles"
    depends_on:
      - sql 
    restart: on-failure:5

  # FRONTEND SERVER
  frontend:
    image: ghcr.io/awaazo/frontend:${FRONTEND_VER}
    container_name: frontend_server
    environment:
      NODE_ENV: production
    ports:
      - "3500:3500"
    links:
      - backend:backend_server
    depends_on:
      - backend
    restart: on-failure:5
