# docker-compose -f docker-compose.macos.m1.yml up --build
version: '3.8'

services:
  # DATABASE (MSSQL)
  sql:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    container_name: sql_server
    platform: linux/arm64
    user: root
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "y"
      MSSQL_SA_PASSWORD: "My.VeryStrongPassword123!"
      SA_PASSWORD: "My.VeryStrongPassword123!"
    volumes:
      - "./data:/var/opt/mssql/data"
    hostname: sql_server
    restart: on-failure:5

  # PYTHON Server (For AI related Stuff)
  # python_backend:
  #   build: 
  #     context: Python/.
  #   container_name: python_server
  #   platform: linux/arm64
  #   ports:
  #     - "8500:8000"
  #   volumes:
  #     - "./backend_server/ServerFiles:/app/ServerFiles" # Modified volume path for macOS


  # BACKEND ASP.NET Server
  backend:
    build:
      context: Backend/Backend/.
      target: final
    container_name: backend_server
    platform: linux/arm64
    ports:
      - "32773:80"
    links:
      - sql:database
      - sql:sql_server
      # - python_backend:py

    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:  
      - "./backend_server/ServerFiles:/app/ServerFiles" # Modified volume path for macOS
    depends_on:
      - sql 
    restart: on-failure:5

  # FRONTEND SERVER
  frontend:
    build: 
      context: frontend/.
    container_name: frontend_server
    environment:
      NODE_ENV: production
    ports:
      - "3500:3500"
    links:
      - backend:backend_server
    depends_on:
      - backend
    restart: on-failure:5
