# This Docker Compose file is used to define and manage the services required for the Awaazo application.
# It sets up the following services:
# - SQL Server: A Microsoft SQL Server container for the database.
# - Python Server: A server for AI-related tasks.
# - Backend ASP.NET Server: The backend server for the Awaazo application.
# - Frontend Server: The frontend server for the Awaazo application.

version: '3.8'

services:

  # DATABASE (MSSQL)
  sql:
    platform: linux/amd64
    image: "mcr.microsoft.com/mssql/server:latest"
    container_name: sql_server
    user: root
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "y"
      SA_PASSWORD: "MyPass@word" # For local dev ONLY. DO NOT SHARE ANY CREDENTIALS
    volumes:
      - "//c/mount/sql:/var/opt/mssql/data"
    restart: on-failure:5

  # PYTHON Server (For AI related Stuff)
  python_backend:
    platform: linux/amd64
    image: ghcr.io/awaazo/py_backend:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    container_name: python_server
    ports:
      - "8500:8000"
    volumes:
      - "//c/backend_server/ServerFiles:/app/ServerFiles"

  # BACKEND ASP.NET Server
  backend:
    platform: linux/amd64
    image: ghcr.io/awaazo/backend:latest
    container_name: backend_server
    ports:
      - "32773:80"
    links:
      - sql:database
      - sql:sql_server
      - python_backend:py
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    volumes:
      - "//c/backend_server/ServerFiles:/app/ServerFiles"
    depends_on:
      - sql 
    restart: on-failure:5

  # FRONTEND SERVER
  frontend:
    platform: linux/amd64
    image: ghcr.io/awaazo/frontend:latest
    container_name: frontend_server
    environment:
      NODE_ENV: production
    ports:
      - "3500:3500"
    links:
      - backend:backend_server
    depends_on:
      - backend
    restart: on-failure:5
