version: '3.8'

services:

  # BACKEND ASP.NET Server
  backend:
    build:
      context: backend/.
      target: final
    container_name: backend_server
    ports:
      - "32773:80"
    links:
      - sql:database
      - sql:sql_server
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - sql 

  # DATABASE (MSSQL)
  sql:
    image: "mcr.microsoft.com/mssql/server:latest"
    container_name: sql_server
    user: root
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "y"
      SA_PASSWORD: "MyPass@word" # For local dev ONLY. DO NOT SHARE ANY CREDENTIALS
    volumes:
      - "//c/mount/sql:/var/opt/mssql/data"

  # FRONTEND SERVER
  frontend:
    build: 
      context: frontend/.
    container_name: frontend_server
    environment:
      NODE_ENV: production
    ports:
      - "3500:3500"
    links:
      - backend:backend_server
    depends_on:
      - backend

  # BACKEND ASP.NET TESTS
  backend-test:
    build: backendTest/.
    container_name: backend_test
    depends_on:
      - sql
    links:
      - sql:database
      - sql:sql_server