name: Build Docker Images

# Only run when PR to main
on:
  pull_request:
    branches:
      - "main"
    paths:
      - "Backend/Backend/**"
      - "frontend/**"
      - "Python/**"
      
jobs:

  # Checks which images have to be build. Only images for which the source code was changed will be build.
  check_changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      py_backend: ${{ steps.filter.outputs.py_backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          py_backend:
            - 'Python/**'
          backend:
            - 'Backend/Backend/**'
          frontend:
            - 'frontend/**'

  # Push frontend Image to Registry
  push_frontend_to_registry:
    name: Push Docker frontend image to github container registry
    needs: check_changes
    if: ${{ needs.check_changes.outputs.frontend == 'true' }}
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/build-frontend-image.yml
  
  # Push Python Image to Registry
  push_python_to_registry:
    name: Push Docker python backend image to github container registry
    needs: check_changes
    if: ${{ needs.check_changes.outputs.py_backend == 'true' }}
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/build-py-image.yml

  # Push Backend Image to Registry
  push_backend_to_registry:
    name: Push Docker backend image to github container registry
    needs: check_changes
    if: ${{ needs.check_changes.outputs.backend == 'true' }}
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/build-backend-image.yml