on:
    workflow_call:
      inputs: 
        package-suffix:
          description: 'A suffix to be appended to the package name'
          default: ''
          required: false
          type: string
        
jobs:
    # Push Backend Image to Registry
    push_backend_to_registry:
      name: Push Docker backend image to github container registry
      runs-on: ubuntu-latest
      permissions:
        packages: write
        contents: read
      steps:

        # Checkout
        - name: Check out the repo
          uses: actions/checkout@v4

          # Add appsettings.json for secrets
        - name: Add Config Backend
          working-directory: Backend/Backend
          env:
            settings: ${{ vars.APPSETTINGSBACKEND }}
          run: |
            touch appsettings.json
            echo $settings > appsettings.json
        
          # Login to Container registy
        - name: Log in to the Container registry
          uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        
        # Extract Data to create the image name
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
          with:
            images: ghcr.io/${{ github.repository_owner }}/backend
            tags: |
              type=ref,event=branch
              type=raw,value={{branch}}
              type=raw,value=latest,enable={{is_default_branch}}

        # Build and push the image to Container Registry
        - name: Build and push Docker images
          uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
          with:
            context: Backend/Backend/.
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}