name: E2E Cypress CI

# Action Triggers
on:
    push:
      branches: 
        - "main"
      paths:
        - "Backend/**"
        - "frontend/**"
        - ".github/workflows/e2e.yml"
    pull_request:
      branches: 
        - "main"
      paths:
        - "Backend/**"
        - "frontend/**"
        - ".github/workflows/e2e.yml"

jobs:
  cypress-run:
    name: End-to-End Testing
    runs-on: ubuntu-latest

    steps:

      #Checkout Changes
      - name: Checkout
        uses: actions/checkout@v3


        # Add appsettings.Development.json + appsettings.json for backend
      - name: Add Config
        working-directory: Backend/Backend
        env:
          settings: ${{ vars.APPSETTINGSBACKEND }}
        run: |
          touch appsettings.Development.json
          touch appsettings.json
          echo $settings > appsettings.Development.json
          echo $settings > appsettings.json

        # Add Env Variables
      - name: Add .env.local
        working-directory: frontend
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: $${{ secrets.GOOGLE_CLIENT_SECRET }}
          BASE_URL: ${{ secrets.BASE_URL }}
          NEXT_AUTH_URL: ${{ secrets.NEXTAUTH }}
          NEXT_PUBLIC_NEXTAUTH_SECRET: ${{ secrets.NEXT_PUBLIC_NEXTAUTH_SECRET }}
        run: |
          touch .env.local
          echo $GOOGLE_CLIENT_ID > .env.local
          echo $GOOGLE_CLIENT_SECRET >> .env.local
          echo $BASE_URL >> .env.local
          echo $NEXT_AUTH_URL >> .env.local
          echo $NEXT_PUBLIC_NEXTAUTH_SECRET >> .env.local

      # Start/Run the Database, Backend API & Frontend Website
      - name: Start Containers
        run: docker-compose -f "docker-compose.yml" up -d --build
      
      # Install Node
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      
      # Install Frontend Deps
      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Run Cypress
        working-directory: frontend
        run: npx cypress run

        
      # # Run the E2E Testing
      # - name: Cypress Run
      #   uses: cypress-io/github-action@v6
      #   with:
      #     working-directory: frontend

      # Upload the Test Results
      - name: Uploading Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: frontend/cypress/screenshots
          if-no-files-found: ignore
      - uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: frontend/cypress/videos
          if-no-files-found: ignore

        
      
