# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Front

# Action Triggers
on:
  push:
    branches: 
      - "main"
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"
  pull_request:
    branches: 
      - "main"
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"
 

jobs:
  buildFrontend:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
  
    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build
  
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
  
    - name: Install dependencies
      run: npm install
  
    - name: Run tests
      run: npm run test
  
    - name: Stop containers
      run: docker-compose -f "docker-compose.yml" down
    